### ISSUE TITLE
Verify 3.0 compatibility

### ISSUE THREAD

**Issue by plauclair** [plauclair/WireMailMailgun#4]
I would really appreciate someone testing this on 3.0 and report how it's working, I don't have much time to test this out right now.

**Comment by plauclair** [comment]
Seems to work well on 3.0, might require more testing.

**Comment by plauclair** [comment]
All seems to be working on my part, let me know if you find issues.

**Comment by cb2004** [comment]
@plauclair seems good for me so far.
