### ISSUE TITLE
send() method return value

### ISSUE THREAD

**Issue by ryancramerdesign** [plauclair/WireMailMailgun#6]
I was running into an issue where email was getting sent, but was getting error messages that it wasn't. I tracked it down to this method, which wasn't passing along the return value:

```
public function send()
{
  $this->___send();
}
```

Updating it to this seems to fix the issue:

```
public function send()
{
  return $this->___send();
}
```

Btw, thanks for the module!

**Comment by plauclair** [comment]
I wasn't sure if this was actually necessary. You're right though send() should return something. What PW version are you running?
